name: Manuscript CI
on:
  push:
  
jobs:
  word_count:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download and extract word counter
        run: wget https://raw.githubusercontent.com/aignas/TeXcount/master/texcount.pl
      - name: Run word counter
        run: perl texcount.pl paper.tex
        
  check_todo:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: grep for TODO or FIXME
        run: |
          grep TODO ./paper.tex & exit 1 | exit 0
          grep FIXME ./paper.tex & exit 1 | exit 0
